name: flutter_local_state_management_comparison
publish_to: "none"
environment:
  sdk: ^3.6.0
version: 0.1.0

workspace:
  - apps/hooks_pattern
  - apps/statefulwidget_pattern
  - packages/common_ui
  - packages/domain
  - packages/repository
  - packages/util

dev_dependencies:
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
