name: util
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.3
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.4
