name: common_ui
description: A starting point for Dart libraries or applications.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  util:
    path: ../../packages/util

dev_dependencies:
  flutter_test:
    sdk: flutter
