name: repository
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  freezed_annotation: ^2.4.4
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.3
