name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.6.0
resolution: workspace

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
